"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['YtDl.py']
DATA_FILES = []
OPTIONS = {
	'iconfile':'logo.icns',
	'argv_emulation': True,
	'packages': ['pytube']
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
